fix WS-Security bookstore services being broken
We were packaging some conflicting dependencies.  In particular,
the WSS4J we were using depends on a conflicting
version of xmlsec and we didn't actually need WSS4j.

We were hitting the following runtime error:
java.lang.NoSuchMethodError: org.apache.xml.security.utils.I18n.init(Ljava/util/ResourceBundle;)V
        at org.apache.wss4j.common.crypto.WSProviderConfig.initializeResourceBundles(WSProviderConfig.java:199) ~[wss4j-ws-security-common-2.1.3.jar:2.1.3]
        at org.apache.wss4j.common.crypto.WSProviderConfig.init(WSProviderConfig.java:65) ~[wss4j-ws-security-common-2.1.3.jar:2.1.3]
        at org.apache.wss4j.dom.WSSConfig.init(WSSConfig.java:345) ~[wss4j-ws-security-dom-2.1.3.jar:2.1.3]
        at org.apache.wss4j.dom.WSSConfig.getNewInstance(WSSConfig.java:354) ~[wss4j-ws-security-dom-2.1.3.jar:2.1.3]
        at org.apache.wss4j.dom.WSSecurityEngine.getWssConfig(WSSecurityEngine.java:152) ~[wss4j-ws-security-dom-2.1.3.jar:2.1.3]
        at org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor.handleMessageInternal(WSS4JInInterceptor.java:209) ~[cxf-rt-ws-security-3.1.3.jar:3.1.3]
        at org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor.handleMessage(WSS4JInInterceptor.java:184) ~[cxf-rt-ws-security-3.1.3.jar:3.1.3]
        at org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor.handleMessage(WSS4JInInterceptor.java:93) ~[cxf-rt-ws-security-3.1.3.jar:3.1.3]